version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:    
    executor: 
      name: node/default
      tag: '14.15.0'
      # Using a fixed node version (latest LTS) to avoid future upgrade issues
    steps:
      - run: node --version 
      - checkout
      - node/install-npm:
          version: 7.0.10
      # Using a fixed npm version to avoid future upgrade issues
      - run: npm --version
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm i      
      - persist_to_workspace:
          root: .
          paths:
            - .
      # Save workspace for subsequent job

  test:
    docker:      
      - image: cimg/node:14.15.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      # Using the same node version as the previous job
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run test
    
  packaging:
    docker:      
      - image: cimg/node:14.15.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Writing build version
          command: 
              export __BUILD_VERSION="$(cat version.txt)"  
      - run:
          name: Compress artifacts
          command: |
            touch artifact.tar
            tar --exclude='./.git' --exclude=artifact.tar -cvzf artifact.tar .
      - store_artifacts:
          path: artifact.tar
      - persist_to_workspace:
          root: .
          paths:
            - artifact.tar

  deploy:
    docker:      
      - image: cimg/node:14.15.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli 
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy to S3
          command: aws s3 cp artifact.tar s3://deploymentbucketappcues/artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - packaging:
          requires:
            - test
      - deploy:
          requires:
            - packaging
